// User
export const
    GET_USERS_REQUEST   = "GET_USERS_REQUEST",
    GET_USERS_FAILURE   = "GET_USERS_FAILURE",
    GET_USERS_SUCCESS   = "GET_USERS_SUCCESS";

// Auth
export const
    AUTH_CHECK_REQUEST  = "AUTH_CHECK_REQUEST",
    AUTH_CHECK_FAILURE  = "AUTH_CHECK_FAILURE",
    AUTH_CHECK_SUCCESS  = "AUTH_CHECK_SUCCESS",
    LOGIN_REQUEST       = "LOGIN_REQUEST",
    LOGIN_FAILURE       = "LOGIN_FAILURE",
    LOGIN_SUCCESS       = "LOGIN_SUCCESS",
    LOGOUT_REQUEST      = "LOGOUT_REQUEST",
    LOGOUT_FAILURE      = "LOGOUT_FAILURE",
    LOGOUT_SUCCESS      = "LOGOUT_SUCCESS";

// @todo: Change to grouped exports
